const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.solid,
		C3.Behaviors.Platform,
		C3.Behaviors.scrollto,
		C3.Plugins.Keyboard,
		C3.Behaviors.Sin,
		C3.Plugins.Audio,
		C3.Plugins.Mouse,
		C3.Plugins.Text,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Behaviors.Platform.Cnds.IsOnFloor,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Audio.Acts.FadeVolume,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Acts.NextPrevLayout,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Sprite.Cnds.IsOverlappingOffset,
		C3.Behaviors.Platform.Acts.SimulateControl,
		C3.Plugins.Mouse.Cnds.OnObjectClicked,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Mouse.Cnds.IsOverObject,
		C3.Plugins.System.Cnds.Else
	];
};
self.C3_JsPropNameTable = [
	{Sólido: 0},
	{ground_01: 0},
	{Plataforma: 0},
	{CentrarEm: 0},
	{Ton: 0},
	{Teclado: 0},
	{plataforma_01: 0},
	{plataforma_02: 0},
	{plataforma_03: 0},
	{Senóide: 0},
	{plataforma_04: 0},
	{orbe: 0},
	{flag: 0},
	{bg_01: 0},
	{bg_02: 0},
	{bg_03: 0},
	{bg_04: 0},
	{death: 0},
	{Áudio: 0},
	{grass_01: 0},
	{grass_02: 0},
	{spike_01: 0},
	{Fade_in: 0},
	{Fade_out: 0},
	{flag_end: 0},
	{Fim_de_jogo: 0},
	{box: 0},
	{Mouse: 0},
	{botao: 0},
	{Texto: 0}
];

self.InstanceType = {
	ground_01: class extends self.ISpriteInstance {},
	Ton: class extends self.ISpriteInstance {},
	Teclado: class extends self.IInstance {},
	plataforma_01: class extends self.ISpriteInstance {},
	plataforma_02: class extends self.ISpriteInstance {},
	plataforma_03: class extends self.ISpriteInstance {},
	plataforma_04: class extends self.ISpriteInstance {},
	orbe: class extends self.ISpriteInstance {},
	flag: class extends self.ISpriteInstance {},
	bg_01: class extends self.ISpriteInstance {},
	bg_02: class extends self.ISpriteInstance {},
	bg_03: class extends self.ISpriteInstance {},
	bg_04: class extends self.ISpriteInstance {},
	death: class extends self.ISpriteInstance {},
	Áudio: class extends self.IInstance {},
	grass_01: class extends self.ISpriteInstance {},
	grass_02: class extends self.ISpriteInstance {},
	spike_01: class extends self.ISpriteInstance {},
	Fade_in: class extends self.ISpriteInstance {},
	Fade_out: class extends self.ISpriteInstance {},
	flag_end: class extends self.ISpriteInstance {},
	Fim_de_jogo: class extends self.ISpriteInstance {},
	box: class extends self.ISpriteInstance {},
	Mouse: class extends self.IInstance {},
	botao: class extends self.ISpriteInstance {},
	Texto: class extends self.ITextInstance {}
}